In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df = pd.read_csv("day_1_groww.csv")

In [17]:
df = df.drop(columns = ["Unnamed: 0"])

In [18]:
df.duplicated().sum()

np.int64(813)

In [19]:
df[df["company_name"] == "Vineet Laboratories"]

,company_name,fund_Market_Cap,fund_ROE,fund_P_E_RatioTTM,fund_EPSTTM,fund_P_B_Ratio,fund_Dividend_Yield,fund_Industry_P_E,fund_Book_Value,fund_Debt_to_Equity,...,price_nse_dayChange,price_nse_dayChangePerc,price_nse_yearLowPrice,price_nse_yearHighPrice,price_bse_yearLowPrice,price_bse_yearHighPrice,details_industryName,details_isFnoEnabled,details_floatingShares,details_isNseFnoEnabled
3225,Vineet Laboratories,₹59Cr,-117.41%,-3.51,-8.69,1.33,0.00%,39.49,23.0,3.01,...,1.72,5.600782,22.37,42.19,21.3,43.56,Pharmaceuticals,False,4726085.0,False
3614,Vineet Laboratories,₹59Cr,-117.41%,-3.51,-8.69,1.33,0.00%,39.49,23.0,3.01,...,1.72,5.600782,22.37,42.19,21.3,43.56,Pharmaceuticals,False,4726085.0,False

In [20]:
df = df.drop_duplicates().reset_index(drop=True)

In [21]:
df.shape

(2802, 26)

In [22]:
df

,company_name,fund_Market_Cap,fund_ROE,fund_P_E_RatioTTM,fund_EPSTTM,fund_P_B_Ratio,fund_Dividend_Yield,fund_Industry_P_E,fund_Book_Value,fund_Debt_to_Equity,...,price_nse_dayChange,price_nse_dayChangePerc,price_nse_yearLowPrice,price_nse_yearHighPrice,price_bse_yearLowPrice,price_bse_yearHighPrice,details_industryName,details_isFnoEnabled,details_floatingShares,details_isNseFnoEnabled
0,Reliance Industries,"₹19,43,807Cr",9.47%,19.88,72.25,2.22,0.38%,15.83,648.28,0.43,...,-14.10,-0.981143,1114.85,1611.8,1115.55,1611.20,Refineries,True,3.405240e+09,True
1,HDFC Bank,"₹14,24,090Cr",13.29%,18.39,50.32,2.54,1.18%,14.32,364.24,NaN,...,-0.10,-0.010801,830.55,1020.5,830.80,1020.35,Banks,True,7.449107e+09,True
2,Bharti Airtel,"₹11,57,185Cr",26.85%,31.23,64.98,9.83,0.80%,37.57,206.50,1.77,...,-9.10,-0.448408,1559.50,2174.5,1561.00,2174.70,Telecom-Service,True,2.257492e+09,True
3,ICICI Bank,"₹10,09,141Cr",15.46%,17.83,79.11,2.95,0.78%,14.32,478.57,NaN,...,-4.10,-0.290451,1200.10,1500.0,1200.20,1494.10,Banks,True,6.850745e+09,True
4,Bajaj Finance,"₹6,30,213Cr",17.73%,34.39,29.45,6.11,0.55%,20.25,165.87,3.85,...,1.40,0.138237,821.13,1102.5,810.21,1102.45,Finance,True,2.446437e+08,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2797,BSE,"₹1,14,231Cr",34.77%,52.27,53.66,21.92,0.27%,52.42,127.93,0.00,...,-62.30,-2.221351,1227.32,3227.0,0.00,0.00,Financial Services,True,1.354629e+08,True
2798,Khadim India,₹280Cr,8.59%,85.56,1.78,1.69,0.00%,48.41,90.20,1.54,...,-2.85,-1.879203,150.50,311.1,150.30,310.70,Leather,False,5.529458e+06,False
2799,Vijaya Diagnostic Centre,"₹10,368Cr",17.53%,64.84,15.54,11.98,0.20%,56.91,84.07,0.42,...,13.30,1.318267,740.00,1180.0,800.00,1179.55,Healthcare,False,4.611646e+07,False
2800,Emkay Global Financial Services,₹608Cr,7.39%,33.71,6.96,1.97,1.67%,31.96,118.96,0.27,...,9.50,4.054631,168.00,409.9,161.55,409.90,Stock/ Commodity Brokers,False,5.425308e+06,False
2801,Arihant Capital Markets,₹782Cr,11.03%,20.20,3.70,1.89,0.67%,31.96,39.64,0.51,...,1.18,1.580710,58.15,120.0,56.31,120.35,Stock/ Commodity Brokers,False,2.396363e+07,False

In [4]:
def clean_and_combine(file_date):
    cleaned_dfs = []
    for file,date in file_date:
        df = pd.read_csv(file)
        df["Date"] = pd.to_datetime(date)
        df = df.drop_duplicates()
        cleaned_dfs.append(df)
    combined = pd.concat(cleaned_dfs,ignore_index=True)
    combined = combined.drop_duplicates().reset_index(drop = True)
    return combined

In [5]:
files = [
    ("day_1_groww.csv", "2026-02-17"),
    ("day_2_groww.csv", "2026-02-18"),
    ("day_3_groww.csv", "2026-02-19"),
    ("day_4_groww.csv", "2026-02-20"),
    ("day_5_groww.csv", "2026-02-23")
]
final_df = clean_and_combine(files)

In [6]:
final_df

,company_name,fund_Market_Cap,fund_ROE,fund_P_E_RatioTTM,fund_EPSTTM,fund_P_B_Ratio,fund_Dividend_Yield,fund_Industry_P_E,fund_Book_Value,fund_Debt_to_Equity,...,price_nse_dayChangePerc,price_nse_yearLowPrice,price_nse_yearHighPrice,price_bse_yearLowPrice,price_bse_yearHighPrice,details_industryName,details_isFnoEnabled,details_floatingShares,details_isNseFnoEnabled,Date
0,Reliance Industries,"₹19,43,807Cr",9.47%,19.88,72.25,2.22,0.38%,15.83,648.28,0.43,...,-0.981143,1114.85,1611.8,1115.55,1611.20,Refineries,True,3.405240e+09,True,2026-02-17
1,HDFC Bank,"₹14,24,090Cr",13.29%,18.39,50.32,2.54,1.18%,14.32,364.24,NaN,...,-0.010801,830.55,1020.5,830.80,1020.35,Banks,True,7.449107e+09,True,2026-02-17
2,Bharti Airtel,"₹11,57,185Cr",26.85%,31.23,64.98,9.83,0.80%,37.57,206.50,1.77,...,-0.448408,1559.50,2174.5,1561.00,2174.70,Telecom-Service,True,2.257492e+09,True,2026-02-17
3,ICICI Bank,"₹10,09,141Cr",15.46%,17.83,79.11,2.95,0.78%,14.32,478.57,NaN,...,-0.290451,1200.10,1500.0,1200.20,1494.10,Banks,True,6.850745e+09,True,2026-02-17
4,Bajaj Finance,"₹6,30,213Cr",17.73%,34.39,29.45,6.11,0.55%,20.25,165.87,3.85,...,0.138237,821.13,1102.5,810.21,1102.45,Finance,True,2.446437e+08,True,2026-02-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13999,BSE,"₹1,11,580Cr",34.77%,51.05,53.66,21.41,0.28%,50.42,127.93,0.00,...,-0.518343,1227.32,3227.0,0.00,0.00,Financial Services,True,1.354629e+08,True,2026-02-23
14000,Khadim India,₹255Cr,8.59%,77.84,1.78,1.54,0.00%,47.00,90.20,1.54,...,-1.582848,135.30,311.1,135.50,310.70,Leather,False,5.529458e+06,False,2026-02-23
14001,Vijaya Diagnostic Centre,"₹10,381Cr",17.53%,64.92,15.54,12.00,0.20%,57.55,84.07,0.42,...,0.411339,813.15,1180.0,800.00,1179.55,Healthcare,False,4.611646e+07,False,2026-02-23
14002,Emkay Global Financial Services,₹610Cr,7.39%,33.88,6.88,1.94,1.66%,31.25,120.24,0.27,...,0.943396,168.00,409.9,161.55,409.90,Stock/ Commodity Brokers,False,5.425308e+06,False,2026-02-23
14003,Arihant Capital Markets,₹784Cr,11.03%,20.26,3.70,1.89,0.66%,31.25,39.64,0.51,...,11.986165,58.15,120.0,56.31,120.35,Stock/ Commodity Brokers,False,2.396363e+07,False,2026-02-23

In [7]:
a = pd.read_csv("day_1_groww.csv")
b = pd.read_csv("day_2_groww.csv")
c = pd.read_csv("day_3_groww.csv")
d = pd.read_csv("day_4_groww.csv")
e = pd.read_csv("day_5_groww.csv")

In [6]:
companies1 = set(a["company_name"].unique())
companies2 = set(b["company_name"].unique())
companies3 = set(c["company_name"].unique())
companies4 = set(d["company_name"].unique())
print(companies1 == companies2 == companies3 == companies4)

False

In [60]:
print("In Day1 but not Day2:", companies1 - companies2)
print("In Day2 but not Day1:", companies2 - companies1)

In Day1 but not Day2: {'AYE Finance', 'Sanmitra Commercial', 'Fractal Analytics', 'Dishman Carbogen Amcis'}
In Day2 but not Day1: {'BLS Infotech', 'Tandhan Industries'}

In [8]:
company_date_counts = final_df.groupby("company_name")["Date"].nunique()

In [9]:
company_date_counts

company_name
AAA Technologies            5
AB Cotspin India            5
AB Infrabuild               5
ABB India                   5
ABC India                   5
                           ..
Zydus Wellness              5
eClerx Services             5
eDynamics Solutions Ltd.    5
eMudhra                     5
iStreet Network             5
Name: Date, Length: 2805, dtype: int64

In [10]:
valid_companies = company_date_counts[company_date_counts == 5].index
final_df = final_df[final_df["company_name"].isin(valid_companies)].reset_index(drop=True)

In [11]:
final_df

,company_name,fund_Market_Cap,fund_ROE,fund_P_E_RatioTTM,fund_EPSTTM,fund_P_B_Ratio,fund_Dividend_Yield,fund_Industry_P_E,fund_Book_Value,fund_Debt_to_Equity,...,price_nse_dayChangePerc,price_nse_yearLowPrice,price_nse_yearHighPrice,price_bse_yearLowPrice,price_bse_yearHighPrice,details_industryName,details_isFnoEnabled,details_floatingShares,details_isNseFnoEnabled,Date
0,Reliance Industries,"₹19,43,807Cr",9.47%,19.88,72.25,2.22,0.38%,15.83,648.28,0.43,...,-0.981143,1114.85,1611.8,1115.55,1611.20,Refineries,True,3.405240e+09,True,2026-02-17
1,HDFC Bank,"₹14,24,090Cr",13.29%,18.39,50.32,2.54,1.18%,14.32,364.24,NaN,...,-0.010801,830.55,1020.5,830.80,1020.35,Banks,True,7.449107e+09,True,2026-02-17
2,Bharti Airtel,"₹11,57,185Cr",26.85%,31.23,64.98,9.83,0.80%,37.57,206.50,1.77,...,-0.448408,1559.50,2174.5,1561.00,2174.70,Telecom-Service,True,2.257492e+09,True,2026-02-17
3,ICICI Bank,"₹10,09,141Cr",15.46%,17.83,79.11,2.95,0.78%,14.32,478.57,NaN,...,-0.290451,1200.10,1500.0,1200.20,1494.10,Banks,True,6.850745e+09,True,2026-02-17
4,Bajaj Finance,"₹6,30,213Cr",17.73%,34.39,29.45,6.11,0.55%,20.25,165.87,3.85,...,0.138237,821.13,1102.5,810.21,1102.45,Finance,True,2.446437e+08,True,2026-02-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13965,BSE,"₹1,11,580Cr",34.77%,51.05,53.66,21.41,0.28%,50.42,127.93,0.00,...,-0.518343,1227.32,3227.0,0.00,0.00,Financial Services,True,1.354629e+08,True,2026-02-23
13966,Khadim India,₹255Cr,8.59%,77.84,1.78,1.54,0.00%,47.00,90.20,1.54,...,-1.582848,135.30,311.1,135.50,310.70,Leather,False,5.529458e+06,False,2026-02-23
13967,Vijaya Diagnostic Centre,"₹10,381Cr",17.53%,64.92,15.54,12.00,0.20%,57.55,84.07,0.42,...,0.411339,813.15,1180.0,800.00,1179.55,Healthcare,False,4.611646e+07,False,2026-02-23
13968,Emkay Global Financial Services,₹610Cr,7.39%,33.88,6.88,1.94,1.66%,31.25,120.24,0.27,...,0.943396,168.00,409.9,161.55,409.90,Stock/ Commodity Brokers,False,5.425308e+06,False,2026-02-23
13969,Arihant Capital Markets,₹784Cr,11.03%,20.26,3.70,1.89,0.66%,31.25,39.64,0.51,...,11.986165,58.15,120.0,56.31,120.35,Stock/ Commodity Brokers,False,2.396363e+07,False,2026-02-23

In [16]:
company_date_counts = final_df.groupby("company_name")["Date"].nunique()

In [18]:
company_date_counts.value_counts()

Date
5    2794
Name: count, dtype: int64

In [19]:
valid_companies = company_date_counts[company_date_counts != 5].index

In [20]:
len(valid_companies)

0

In [21]:
final_df.to_csv("final_groww_5days.csv")

In [22]:
final_df

,company_name,fund_Market_Cap,fund_ROE,fund_P_E_RatioTTM,fund_EPSTTM,fund_P_B_Ratio,fund_Dividend_Yield,fund_Industry_P_E,fund_Book_Value,fund_Debt_to_Equity,...,price_nse_dayChangePerc,price_nse_yearLowPrice,price_nse_yearHighPrice,price_bse_yearLowPrice,price_bse_yearHighPrice,details_industryName,details_isFnoEnabled,details_floatingShares,details_isNseFnoEnabled,Date
0,Reliance Industries,"₹19,43,807Cr",9.47%,19.88,72.25,2.22,0.38%,15.83,648.28,0.43,...,-0.981143,1114.85,1611.8,1115.55,1611.20,Refineries,True,3.405240e+09,True,2026-02-17
1,HDFC Bank,"₹14,24,090Cr",13.29%,18.39,50.32,2.54,1.18%,14.32,364.24,NaN,...,-0.010801,830.55,1020.5,830.80,1020.35,Banks,True,7.449107e+09,True,2026-02-17
2,Bharti Airtel,"₹11,57,185Cr",26.85%,31.23,64.98,9.83,0.80%,37.57,206.50,1.77,...,-0.448408,1559.50,2174.5,1561.00,2174.70,Telecom-Service,True,2.257492e+09,True,2026-02-17
3,ICICI Bank,"₹10,09,141Cr",15.46%,17.83,79.11,2.95,0.78%,14.32,478.57,NaN,...,-0.290451,1200.10,1500.0,1200.20,1494.10,Banks,True,6.850745e+09,True,2026-02-17
4,Bajaj Finance,"₹6,30,213Cr",17.73%,34.39,29.45,6.11,0.55%,20.25,165.87,3.85,...,0.138237,821.13,1102.5,810.21,1102.45,Finance,True,2.446437e+08,True,2026-02-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13965,BSE,"₹1,11,580Cr",34.77%,51.05,53.66,21.41,0.28%,50.42,127.93,0.00,...,-0.518343,1227.32,3227.0,0.00,0.00,Financial Services,True,1.354629e+08,True,2026-02-23
13966,Khadim India,₹255Cr,8.59%,77.84,1.78,1.54,0.00%,47.00,90.20,1.54,...,-1.582848,135.30,311.1,135.50,310.70,Leather,False,5.529458e+06,False,2026-02-23
13967,Vijaya Diagnostic Centre,"₹10,381Cr",17.53%,64.92,15.54,12.00,0.20%,57.55,84.07,0.42,...,0.411339,813.15,1180.0,800.00,1179.55,Healthcare,False,4.611646e+07,False,2026-02-23
13968,Emkay Global Financial Services,₹610Cr,7.39%,33.88,6.88,1.94,1.66%,31.25,120.24,0.27,...,0.943396,168.00,409.9,161.55,409.90,Stock/ Commodity Brokers,False,5.425308e+06,False,2026-02-23
13969,Arihant Capital Markets,₹784Cr,11.03%,20.26,3.70,1.89,0.66%,31.25,39.64,0.51,...,11.986165,58.15,120.0,56.31,120.35,Stock/ Commodity Brokers,False,2.396363e+07,False,2026-02-23

In [23]:
df = pd.read_csv("final_groww_4days.csv")

In [24]:
df.isna().sum()

Unnamed: 0                    0
company_name                  0
fund_Market_Cap             136
fund_ROE                    148
fund_P_E_RatioTTM           136
fund_EPSTTM                 136
fund_P_B_Ratio              136
fund_Dividend_Yield         136
fund_Industry_P_E           136
fund_Book_Value             136
fund_Debt_to_Equity         300
price_nse_ltp              4690
price_nse_open             4690
price_nse_close            4690
price_nse_high             4690
price_nse_low              4690
price_nse_volume           4690
price_nse_dayChange        4690
price_nse_dayChangePerc    4690
price_nse_yearLowPrice      456
price_nse_yearHighPrice     456
price_bse_yearLowPrice      456
price_bse_yearHighPrice     456
details_industryName        136
details_isFnoEnabled        660
details_floatingShares     2312
details_isNseFnoEnabled       0
Date                          0
dtype: int64

In [3]:
df = pd.read_csv("final_groww_4days.csv")

In [4]:
df.shape

(11188, 28)

In [5]:
2800 * 4

11200

In [11]:
df.duplicated().sum()

np.int64(0)

In [9]:
df = df.drop(columns=["Unnamed: 0"])

,company_name,fund_Market_Cap,fund_ROE,fund_P_E_RatioTTM,fund_EPSTTM,fund_P_B_Ratio,fund_Dividend_Yield,fund_Industry_P_E,fund_Book_Value,fund_Debt_to_Equity,...,price_nse_dayChangePerc,price_nse_yearLowPrice,price_nse_yearHighPrice,price_bse_yearLowPrice,price_bse_yearHighPrice,details_industryName,details_isFnoEnabled,details_floatingShares,details_isNseFnoEnabled,Date
0,Reliance Industries,"₹19,43,807Cr",9.47%,19.88,72.25,2.22,0.38%,15.83,648.28,0.43,...,-0.981143,1114.85,1611.8,1115.55,1611.20,Refineries,True,3.405240e+09,True,2026-02-17
1,HDFC Bank,"₹14,24,090Cr",13.29%,18.39,50.32,2.54,1.18%,14.32,364.24,NaN,...,-0.010801,830.55,1020.5,830.80,1020.35,Banks,True,7.449107e+09,True,2026-02-17
2,Bharti Airtel,"₹11,57,185Cr",26.85%,31.23,64.98,9.83,0.80%,37.57,206.50,1.77,...,-0.448408,1559.50,2174.5,1561.00,2174.70,Telecom-Service,True,2.257492e+09,True,2026-02-17
3,ICICI Bank,"₹10,09,141Cr",15.46%,17.83,79.11,2.95,0.78%,14.32,478.57,NaN,...,-0.290451,1200.10,1500.0,1200.20,1494.10,Banks,True,6.850745e+09,True,2026-02-17
4,Bajaj Finance,"₹6,30,213Cr",17.73%,34.39,29.45,6.11,0.55%,20.25,165.87,3.85,...,0.138237,821.13,1102.5,810.21,1102.45,Finance,True,2.446437e+08,True,2026-02-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11183,BSE,"₹1,11,657Cr",34.77%,51.09,53.66,21.43,0.28%,51.20,127.93,0.00,...,-0.069308,1227.32,3227.0,0.00,0.00,Financial Services,True,1.354629e+08,True,2026-02-20
11184,Khadim India,₹254Cr,8.59%,77.67,1.78,1.53,0.00%,48.20,90.20,1.54,...,0.506183,137.50,311.1,138.00,310.70,Leather,False,5.529458e+06,False,2026-02-20
11185,Vijaya Diagnostic Centre,"₹10,387Cr",17.53%,64.96,15.54,12.01,0.20%,57.88,84.07,0.42,...,-0.059435,813.15,1180.0,800.00,1179.55,Healthcare,False,4.611646e+07,False,2026-02-20
11186,Emkay Global Financial Services,₹605Cr,7.39%,33.57,6.96,1.96,1.68%,31.76,118.96,0.27,...,-1.123596,168.00,409.9,161.55,409.90,Stock/ Commodity Brokers,False,5.425308e+06,False,2026-02-20
11187,Arihant Capital Markets,₹798Cr,11.03%,20.62,3.70,1.92,0.65%,31.76,39.64,0.51,...,-1.261001,58.15,120.0,56.31,120.35,Stock/ Commodity Brokers,False,2.396363e+07,False,2026-02-20

In [14]:
df = pd.read_csv("final_groww_4days.csv")

In [15]:
df

,company_name,fund_Market_Cap,fund_ROE,fund_P_E_RatioTTM,fund_EPSTTM,fund_P_B_Ratio,fund_Dividend_Yield,fund_Industry_P_E,fund_Book_Value,fund_Debt_to_Equity,...,price_nse_dayChangePerc,price_nse_yearLowPrice,price_nse_yearHighPrice,price_bse_yearLowPrice,price_bse_yearHighPrice,details_industryName,details_isFnoEnabled,details_floatingShares,details_isNseFnoEnabled,Date
0,Reliance Industries,"₹19,43,807Cr",9.47%,19.88,72.25,2.22,0.38%,15.83,648.28,0.43,...,-0.981143,1114.85,1611.8,1115.55,1611.20,Refineries,True,3.405240e+09,True,17-02-2026
1,HDFC Bank,"₹14,24,090Cr",13.29%,18.39,50.32,2.54,1.18%,14.32,364.24,NaN,...,-0.010801,830.55,1020.5,830.80,1020.35,Banks,True,7.449107e+09,True,17-02-2026
2,Bharti Airtel,"₹11,57,185Cr",26.85%,31.23,64.98,9.83,0.80%,37.57,206.50,1.77,...,-0.448408,1559.50,2174.5,1561.00,2174.70,Telecom-Service,True,2.257492e+09,True,17-02-2026
3,ICICI Bank,"₹10,09,141Cr",15.46%,17.83,79.11,2.95,0.78%,14.32,478.57,NaN,...,-0.290451,1200.10,1500.0,1200.20,1494.10,Banks,True,6.850745e+09,True,17-02-2026
4,Bajaj Finance,"₹6,30,213Cr",17.73%,34.39,29.45,6.11,0.55%,20.25,165.87,3.85,...,0.138237,821.13,1102.5,810.21,1102.45,Finance,True,2.446437e+08,True,17-02-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11183,BSE,"₹1,11,657Cr",34.77%,51.09,53.66,21.43,0.28%,51.20,127.93,0.00,...,-0.069308,1227.32,3227.0,0.00,0.00,Financial Services,True,1.354629e+08,True,20-02-2026
11184,Khadim India,₹254Cr,8.59%,77.67,1.78,1.53,0.00%,48.20,90.20,1.54,...,0.506183,137.50,311.1,138.00,310.70,Leather,False,5.529458e+06,False,20-02-2026
11185,Vijaya Diagnostic Centre,"₹10,387Cr",17.53%,64.96,15.54,12.01,0.20%,57.88,84.07,0.42,...,-0.059435,813.15,1180.0,800.00,1179.55,Healthcare,False,4.611646e+07,False,20-02-2026
11186,Emkay Global Financial Services,₹605Cr,7.39%,33.57,6.96,1.96,1.68%,31.76,118.96,0.27,...,-1.123596,168.00,409.9,161.55,409.90,Stock/ Commodity Brokers,False,5.425308e+06,False,20-02-2026
11187,Arihant Capital Markets,₹798Cr,11.03%,20.62,3.70,1.92,0.65%,31.76,39.64,0.51,...,-1.261001,58.15,120.0,56.31,120.35,Stock/ Commodity Brokers,False,2.396363e+07,False,20-02-2026

In [35]:
sector_to_industries = {
    'Financial': [
        'Finance', 'Trading', 'Stock/ Commodity Brokers', 
        'Financial Services', 'Insurance', 'Credit Rating Agencies'
    ],
    'Banking': ['Banks'],
    'IT Industry': [
        'IT - Software', 'IT - Hardware', 'Computer Education', 
        'E-Commerce/App based Aggregator', 'Electronics'
    ],
    'Healthcare': ['Pharmaceuticals', 'Healthcare'],
    'FMCG': ['FMCG', 'Retail', 'Edible Oil', 'Alcoholic Beverages', 'Tobacco Products'],
    'Consumer Durables': ['Consumer Durables'],
    'Automobiles & Ancillaries': ['Automobile', 'Auto Ancillaries'],
    'Logistic & Freight': ['Logistics', 'Marine Port & Services'],
    'Hospitality & Travel': [
        'Quick Service Restaurant', 'Air Transport Service', 
        'Shipping', 'Hotels & Restaurants'
    ],
    'Derived Materials': [
        'Chemicals', 'Paints/Varnish', 'Plastic products', 
        'Glass & Glass Products', 'Ceramic Products', 
        'Non Ferrous Metals', 'Paper', 'Ferro Alloys'
    ],
    'Industries': [
        'Steel', 'Realty', 'Infrastructure Developers & Operators', 'Construction'
    ],
    'Industrial Products': [
        'Capital Goods-Non Electrical Equipment', 'Capital Goods - Electrical Equipment', 
        'Castings, Forgings & Fastners', 'Packaging', 'Engineering', 
        'Refractories', 'Tyres', 'Bearings', 'Cables', 
        'Plywood Boards/Laminates', 'Ship Building', 'Cement - Products',
        'Printing & Stationery', 'Dry cells', 'Aerospace & Defence'
    ],
    'Raw Material': ['Cement', 'Mining & Mineral products'],
    'Textile Industry': ['Textiles'],
    'Apparel & Accessories': ['Leather', 'Readymade Garments/ Apparells'],
    'Media & Entertainment': ['Media - Print/Television/Radio', 'Entertainment', 'Education'],
    'Energy': [
        'Crude Oil & Natural Gas', 'Petrochemicals', 'Refineries', 
        'Power Generation & Distribution', 'Gas Distribution', 'Power Infrastructure',
        'Oil Drill/Allied'
    ],
    'Agricultural': ['Agro Chemicals', 'Fertilizers', 'Sugar', 'Plantation & Plantation Products'],
    'Tele-Communication': ['Telecom-Service', 'Telecom Equipment & Infra Services'],
    'Others': ['Miscellaneous', 'Diversified', 'Diamond, Gems and Jewellery', 'Co-Working']
}

In [36]:
industry_to_sector = {}
for sec,ind in sector_to_industries.items():
    for i in ind:
        industry_to_sector[i] = sec

In [37]:
df["sector"] = df["details_industryName"].map(industry_to_sector)

In [38]:
df

,company_name,fund_Market_Cap,fund_ROE,fund_P_E_RatioTTM,fund_EPSTTM,fund_P_B_Ratio,fund_Dividend_Yield,fund_Industry_P_E,fund_Book_Value,fund_Debt_to_Equity,...,price_nse_yearLowPrice,price_nse_yearHighPrice,price_bse_yearLowPrice,price_bse_yearHighPrice,details_industryName,details_isFnoEnabled,details_floatingShares,details_isNseFnoEnabled,Date,sector
0,Reliance Industries,"₹19,43,807Cr",9.47%,19.88,72.25,2.22,0.38%,15.83,648.28,0.43,...,1114.85,1611.8,1115.55,1611.20,Refineries,True,3.405240e+09,True,17-02-2026,Energy
1,HDFC Bank,"₹14,24,090Cr",13.29%,18.39,50.32,2.54,1.18%,14.32,364.24,NaN,...,830.55,1020.5,830.80,1020.35,Banks,True,7.449107e+09,True,17-02-2026,Banking
2,Bharti Airtel,"₹11,57,185Cr",26.85%,31.23,64.98,9.83,0.80%,37.57,206.50,1.77,...,1559.50,2174.5,1561.00,2174.70,Telecom-Service,True,2.257492e+09,True,17-02-2026,Tele-Communication
3,ICICI Bank,"₹10,09,141Cr",15.46%,17.83,79.11,2.95,0.78%,14.32,478.57,NaN,...,1200.10,1500.0,1200.20,1494.10,Banks,True,6.850745e+09,True,17-02-2026,Banking
4,Bajaj Finance,"₹6,30,213Cr",17.73%,34.39,29.45,6.11,0.55%,20.25,165.87,3.85,...,821.13,1102.5,810.21,1102.45,Finance,True,2.446437e+08,True,17-02-2026,Financial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11183,BSE,"₹1,11,657Cr",34.77%,51.09,53.66,21.43,0.28%,51.20,127.93,0.00,...,1227.32,3227.0,0.00,0.00,Financial Services,True,1.354629e+08,True,20-02-2026,Financial
11184,Khadim India,₹254Cr,8.59%,77.67,1.78,1.53,0.00%,48.20,90.20,1.54,...,137.50,311.1,138.00,310.70,Leather,False,5.529458e+06,False,20-02-2026,Apparel & Accessories
11185,Vijaya Diagnostic Centre,"₹10,387Cr",17.53%,64.96,15.54,12.01,0.20%,57.88,84.07,0.42,...,813.15,1180.0,800.00,1179.55,Healthcare,False,4.611646e+07,False,20-02-2026,Healthcare
11186,Emkay Global Financial Services,₹605Cr,7.39%,33.57,6.96,1.96,1.68%,31.76,118.96,0.27,...,168.00,409.9,161.55,409.90,Stock/ Commodity Brokers,False,5.425308e+06,False,20-02-2026,Financial
11187,Arihant Capital Markets,₹798Cr,11.03%,20.62,3.70,1.92,0.65%,31.76,39.64,0.51,...,58.15,120.0,56.31,120.35,Stock/ Commodity Brokers,False,2.396363e+07,False,20-02-2026,Financial

In [40]:
a = df["sector"].isna().sum()

In [44]:
df["details_industryName"].isna().sum()

np.int64(136)

In [34]:
df["details_industryName"].value_counts().index

Index(['Finance', 'Trading', 'Textiles', 'IT - Software', 'Pharmaceuticals',
       'Chemicals', 'Realty', 'FMCG', 'Steel',
       'Capital Goods-Non Electrical Equipment', 'Auto Ancillaries',
       'Miscellaneous', 'Infrastructure Developers & Operators',
       'Consumer Durables', 'Capital Goods - Electrical Equipment',
       'Healthcare', 'Plastic products', 'Hotels & Restaurants', 'Retail',
       'Diamond, Gems and Jewellery', 'Packaging', 'Banks', 'Entertainment',
       'Castings, Forgings & Fastners', 'Non Ferrous Metals', 'Logistics',
       'Stock/ Commodity Brokers', 'Cement', 'Power Generation & Distribution',
       'Construction', 'E-Commerce/App based Aggregator',
       'Aerospace & Defence', 'Sugar', 'Automobile', 'Agro Chemicals',
       'Diversified', 'Paper', 'Cables', 'Leather',
       'Mining & Mineral products', 'Alcoholic Beverages', 'Engineering',
       'Plywood Boards/Laminates', 'Plantation & Plantation Products',
       'Edible Oil', 'Readymade Garments/ Apparells', 'Telecom-Service',
       'Printing & Stationery', 'Education', 'Tyres',
       'Media - Print/Television/Radio', 'Ceramic Products', 'Petrochemicals',
       'Insurance', 'IT - Hardware', 'Electronics', 'Bearings', 'Fertilizers',
       'Gas Distribution', 'Telecom Equipment & Infra Services',
       'Refractories', 'Crude Oil & Natural Gas', 'Glass & Glass Products',
       'Paints/Varnish', 'Computer Education', 'Refineries', 'Shipping',
       'Quick Service Restaurant', 'Financial Services', 'Cement - Products',
       'Tobacco Products', 'Co-Working', 'Ferro Alloys',
       'Credit Rating Agencies', 'Air Transport Service',
       'Marine Port & Services', 'Ship Building', 'Oil Drill/Allied',
       'Dry cells', 'Power Infrastructure'],
      dtype='object', name='details_industryName')

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11188 entries, 0 to 11187
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   company_name             11188 non-null  object
 1   fund_Market_Cap          11052 non-null  object
 2   fund_ROE                 11040 non-null  object
 3   fund_P_E_RatioTTM        11052 non-null  float64
 4   fund_EPSTTM              11052 non-null  float64
 5   fund_P_B_Ratio           11052 non-null  float64
 6   fund_Dividend_Yield      11052 non-null  object
 7   fund_Industry_P_E        11052 non-null  float64
 8   fund_Book_Value          11052 non-null  float64
 9   fund_Debt_to_Equity      10888 non-null  float64
 10  price_nse_ltp            6498 non-null   float64
 11  price_nse_open           6498 non-null   float64
 12  price_nse_close          6498 non-null   float64
 13  price_nse_high           6498 non-null   float64
 14  price_nse_low            6498 non-null   float64
 15  price_nse_volume         6498 non-null   float64
 16  price_nse_dayChange      6498 non-null   float64
 17  price_nse_dayChangePerc  6498 non-null   float64
 18  price_nse_yearLowPrice   10732 non-null  float64
 19  price_nse_yearHighPrice  10732 non-null  float64
 20  price_bse_yearLowPrice   10732 non-null  float64
 21  price_bse_yearHighPrice  10732 non-null  float64
 22  details_industryName     11052 non-null  object
 23  details_isFnoEnabled     10528 non-null  object
 24  details_floatingShares   8876 non-null   float64
 25  details_isNseFnoEnabled  11188 non-null  bool
 26  Date                     11188 non-null  object
 27  sector                   11052 non-null  object
dtypes: bool(1), float64(19), object(8)
memory usage: 2.3+ MB